local Settings = {
	canAim = true;
	isdrop = false;

	aimSmooth = 0.4;
	fireAnim = 'rbxassetid://90619616789344';
	loadAnim = 'rbxassetid://78121633556951'; 
	RealodAnim = 'rbxassetid://97684544131717';
	IdleAnim = 'rbxassetid://97072364218061';
	fireServer = 'rbxassetid://103459512593554';

	sound = game:GetService('SoundService'):WaitForChild('ak74shot');
	damage = 60;
	headshot = 200;


	fireRate = 0.1, -- Time between shots (seconds) when holding Auto
	GunName = 'Ak-74';
	sprintCF = CFrame.new(0, 0, 0) * CFrame.Angles(math.rad(-90/10), math.rad(0), math.rad(0));
	Ammo = 60;
	MaxAmmo= 200;

	-- Fire Modes Setup
	currentFireMode = "Semi"; -- The mode the gun starts with
	availableModes = {
		"Semi",
		"Auto"
	};
}


return Settings
